# Generated by Django 3.0.4 on 2020-04-29 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orgs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('invoice_to', models.CharField(max_length=256)),
                ('org_id', models.CharField(default=orgs.models.hex_uuid, max_length=64)),
                ('is_legacy_customer', models.BooleanField(default=False)),
                ('usage_tracking_method', models.CharField(blank=True, max_length=128, null=True)),
                ('external_service', models.CharField(blank=True, max_length=128, null=True)),
                ('external_service_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopes', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_users', to='orgs.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
