# Generated by Django 3.0.4 on 2020-04-29 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.IntegerField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
                ('payment_id', models.CharField(max_length=255)),
                ('abandoned', models.DateTimeField(verbose_name='abandoned date')),
                ('payment_status', models.CharField(choices=[('IMPORTED', 'Imported'), ('PENDING', 'Pending'), ('LOW_BALANCE', 'Low Balance'), ('REJECTED', 'Rejected'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete')], db_index=True, default='PENDING', max_length=32)),
                ('billing_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='billing.BillingInfo')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('media_length_ms', models.IntegerField(default=0)),
                ('final_price', models.FloatField(default=0.0)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Cart')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='library.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_language', models.CharField(max_length=255, null=True)),
                ('target_languages', models.CharField(max_length=255, null=True)),
                ('turnaround_time', models.CharField(default='STD', max_length=255)),
                ('rush_12', models.BooleanField(default=False)),
                ('rush_24', models.BooleanField(default=False)),
                ('true_verbatim', models.BooleanField(default=False)),
                ('speaker_id', models.BooleanField(default=False)),
                ('job_type', models.CharField(default='TX', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('global_default', models.BooleanField(default=False)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='billing.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_presets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutputProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_paths', models.TextField(default='{}')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_entries', to='library.Entry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_output_products', to='orders.OrderItem')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='presets_selected',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_presets', to='orders.Preset'),
        ),
    ]
