# Generated by Django 3.0.4 on 2020-04-30 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20200430_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='preset',
            name='source_language',
            field=models.CharField(default='en', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preset',
            name='target_languages',
            field=models.CharField(default='en', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_presets', to=settings.AUTH_USER_MODEL),
        ),
    ]
