# Generated by Django 3.0.4 on 2020-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200501_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(blank=True, default='Payment Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outputproduct',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outputproduct',
            name='status',
            field=models.CharField(blank=True, default='DISPATCHED', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
